### ISSUE TITLE
Vertex AI Automl training error when training dataset with foreign project's BQ table as source

### ISSUE THREAD

**Issue by kavigithib** [googleapis/python-aiplatform#1078]
### Issue in Vertex AI Automl training python API while using vertex dataset with source as foreign project's BQ table
- What would you like to achieve: I would like to run automl training job(using automl api python) with vertex dataset created from foreign project's BigQuery table.
- Even though 'vertex AI service agent' and 'Vertex AI Custom code service agent' added to respective bigquery dataset with 'bigquery data editor' role, we are receiving bigquery.tables.get persmission denied error when we try run automl training job. 

Error:
`INFO:google.cloud.aiplatform.training_jobs:No column transformations provided, so now retrieving columns from dataset in order to set default column transformations. 
Traceback (most recent call last): 
File "/home/vsts/work/1/a/.terraform/modules/gcp_automl/scripts/train_automl.py", line 190, in <module> 
automl_tabular = create_training_pipeline_tabular(train_type, project_id, display_name, int(dataset_id), location, model_display_name, float(training_fraction_split), float(validation_fraction_split), float(test_fraction_split), int(budget_milli_node_hours), disable_early_stopping, sync, target_column) 
File "/home/vsts/work/1/a/.terraform/modules/gcp_automl/scripts/train_automl.py", line 57, in create_training_pipeline_tabular 
model = tabular_job.run( 
File "/home/vsts/.local/lib/python3.8/site-packages/google/cloud/aiplatform/training_jobs.py", line 3461, in run 
return self._run( 
File "/home/vsts/.local/lib/python3.8/site-packages/google/cloud/aiplatform/base.py", line 730, in wrapper 
return method(*args, **kwargs) 
File "/home/vsts/.local/lib/python3.8/site-packages/google/cloud/aiplatform/training_jobs.py", line 3645, in _run 
) = column_transformations_utils.get_default_column_transformations( 
File "/home/vsts/.local/lib/python3.8/site-packages/google/cloud/aiplatform/utils/column_transformations_utils.py", line 42, in get_default_column_transformations 
for column_name in dataset.column_names 
File "/home/vsts/.local/lib/python3.8/site-packages/google/cloud/aiplatform/datasets/column_names_dataset.py", line 81, in column_names 
self._retrieve_bq_source_columns( 
File "/home/vsts/.local/lib/python3.8/site-packages/google/cloud/aiplatform/datasets/column_names_dataset.py", line 241, in _retrieve_bq_source_columns 
table = client.get_table(bq_table_uri) 
File "/home/vsts/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 1034, in get_table 
api_response = self._call_api( 
File "/home/vsts/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 782, in _call_api 
return call() 
File "/home/vsts/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func 
return retry_target( 
File "/home/vsts/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 190, in retry_target 
return target() 
File "/home/vsts/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 480, in api_request 
raise exceptions.from_http_response(response) 
google.api_core.exceptions.Forbidden: 403 GET https://bigquery.googleapis.com/bigquery/v2/projects/<<projectID>>/datasets/<<datasetID>>/tables/<<tableID>>?prettyPrint=false: Access Denied: Table <<TableID>>: Permission bigquery.tables.get denied on table <<TableID>> (or it may not exist). 
`

After raising google support, we got a temporary workaround by adding column specification in API call (reference case# 29535929, 29310889).
**Sample API call of the workaround:**
`job = training_jobs.AutoMLTabularTrainingJob( 
display_name="my_display_name", 
optimization_prediction_type="classification", 
optimization_objective="minimize-log-loss", 
column_specs={"column_1": "auto", "column_2": "numeric"}, 
labels={'key': 'value'}, 
) 
`

We would want to have this fixed in in SDK. If possible, we would like to have a gcloud command for automl modules.

**Comment by sararob** [comment]
I've updated the docstring to clarify that the service account needs certain permissions when neither `column_transformations` or `column_specs` is set.
