### ISSUE TITLE
AttributeError: module 'queue' has no attribute 'SimpleQueue'

### ISSUE THREAD

**Issue by hasibeg** [googleapis/python-aiplatform#1402]
Hello team,

I'm using the sample function to run an automl model prediction.
https://github.com/googleapis/python-aiplatform/blob/main/samples/snippets/prediction_service/predict_image_object_detection_sample.py
I receive the following error about python (tried it with python 3.7 and 3.8)
  --> AttributeError: module 'queue' has no attribute 'SimpleQueue'

I managed to run this code few months ago without any problems. So I'm not sure what could be the issue.. I looked at this attribute problem in  the internet and the solutions were all about upgrading to python 3.7 which is already what I am using.
#### Environment details

  - OS type and version:
  - Python version: Python 3.8.9 and Python 3.7.9
  - pip version: 
  pip 22.1.1 from /Users/hasibe/Library/Python/3.8/lib/python/site-packages/pip (python 3.8)
  pip 22.1.1 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)
  - `google-cloud-aiplatform` version: `pip show google-cloud-aiplatform`
Name: google-cloud-aiplatform
Version: 1.13.1
Summary: Vertex AI API client library
Home-page: https://github.com/googleapis/python-aiplatform
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/hasibe/Library/Python/3.8/lib/python/site-packages
Requires: google-api-core, google-cloud-bigquery, google-cloud-resource-manager, google-cloud-storage, packaging, proto-plus
Required-by:

#### Steps to reproduce

  1. /usr/local/bin/python3 -m pip install google-cloud-aiplatform
  2. /usr/local/bin/python3 /..../automl.py.  (this is the code that I have the prediction function and I call that function with the piece of code provided in the model page in GCP)

#### Code example

```python
# example
https://github.com/googleapis/python-aiplatform/blob/main/samples/snippets/prediction_service/predict_image_object_detection_sample.py
++ 
predict_image_object_detection_sample(
    project="....",
    endpoint_id=".....",
    location="us-central1",
    filename="....png"
)
```

#### Stack trace
Traceback (most recent call last):
  File "/Users/hasibe/Desktop/Coding/Test/automl.py", line 18, in <module>
    from google.cloud import aiplatform
  File "/Users/hasibe/Library/Python/3.8/lib/python/site-packages/google/cloud/aiplatform/__init__.py", line 24, in <module>
    from google.cloud.aiplatform import initializer
  File "/Users/hasibe/Library/Python/3.8/lib/python/site-packages/google/cloud/aiplatform/initializer.py", line 327, in <module>
    global_pool = futures.ThreadPoolExecutor(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 147, in __init__
    self._work_queue = queue.SimpleQueue()
AttributeError: module 'queue' has no attribute 'SimpleQueue'

**Comment by hasibeg** [comment]
User issue..
