### ISSUE TITLE
Endpoint.deploy setting autoscaling_target_cpu_utilization error

### ISSUE THREAD

**Issue by entrpn** [googleapis/python-aiplatform#1669]
#### Environment details

  - OS type and version: Debian GNU/Linux 10 (buster)
  - Python version: 3.7.12
  - pip version: 22.0.2
  - `google-cloud-aiplatform` version: 1.17.0

#### Steps to reproduce

  1. I have a deployment script that fails when I set the `autoscaling_target_cpu_utilization` in `endpoint.deploy`. If I don't set this value, the script works.

#### Code example

```python
import argparse
from google.cloud import aiplatform

def main(opt):

    models = aiplatform.Model.list()
    model_found = False
    for model in models:
        
        if model.display_name == opt.model_name:
            print(model.resource_name)
            model_found = True
            break
    
    if not model_found:
        print("No model found, creating...")
        model = aiplatform.Model.upload(
            display_name=opt.model_name,
            serving_container_image_uri=opt.image_uri,
            serving_container_ports=[8080],
            serving_container_predict_route="/predict"
        )

    endpoints = aiplatform.Endpoint.list()
    endpoint_found = False
    for endpoint in endpoints:
        if endpoint.display_name == opt.endpoint_name:
            print(endpoint.resource_name)
            endpoint_found = True
            break    
    
    if not endpoint_found:
        print("No endpoint found, creating...")
        endpoint = aiplatform.Endpoint.create(
            display_name=opt.endpoint_name,
            create_request_timeout=300.0
        )
    print(vars(endpoint)) 
    models = endpoint.list_models()
    if len(models) > 0:
        print("undeploying previous models...")
        endpoint.undeploy_all()

    #NVIDIA_TESLA_V100
    #NVIDIA_TESLA_T4
    endpoint.deploy(
        model,
        deployed_model_display_name="mode_name_endpoint_deployed",
        traffic_percentage=100,
        machine_type=opt.machine_type,
        min_replica_count=opt.min_replica_count,
        max_replica_count=opt.max_replica_count,
        accelerator_type=opt.gpu_type,
        accelerator_count=opt.accelerator_count,
        sync=True,
        deploy_request_timeout=300.0,
        autoscaling_target_cpu_utilization=10
    )

    print("done")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        '--min-replica-count',
        type=int,
        default=1,
        help='Minimum number of replicas'
    )
    parser.add_argument(
        '--machine-type',
        type=str,
        default='n1-standard-2',
        help='Machine type'
    )
    parser.add_argument(
        '--max-replica-count',
        type=int,
        default=1,
        help='Maximum number of replicas'
    )
    parser.add_argument(
        "--gpu-type",
        type=str,
        default='NVIDIA_TESLA_T4',
        help="GPU type"
    )
    parser.add_argument(
        "--accelerator-count",
        type=int,
        default=1,
        help="GPU count"
    )
    parser.add_argument(
        "--region",
        type=str,
        default="us-central1",
        help="gcp region"
    )
    parser.add_argument(
        "--model-name",
        type=str,
        default="mode-name",
        help="name of model"        
    )
    parser.add_argument(
        "--endpoint-name",
        type=str,
        default="model-name-endpoint",
        help="Name of endpoint"        
    )
    parser.add_argument(
        "--endpoint-deployed-name",
        type=str,
        default="model_name_endpoint_deployed",
        help="Endpoint deployed name"
    )
    parser.add_argument(
        "--image-uri",
        type=str,
        required=True,
        help="name of image in gcr. Ex: gcr.io/project-name/image:latest"
    )

    opt = parser.parse_args()
    main(opt)
```

Deployed via

```python
python gcp_deploy.py --image-uri gcr.io/{project_id}/image-name:latest --min-replica-count 1 --max-replica-count 3
```

#### Stack trace
```
Traceback (most recent call last):
  File "gcp_deploy.py", line 127, in <module>
    main(opt)
  File "gcp_deploy.py", line 57, in main
    autoscaling_target_cpu_utilization=10
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/models.py", line 839, in deploy
    autoscaling_target_accelerator_duty_cycle=autoscaling_target_accelerator_duty_cycle,
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/base.py", line 806, in wrapper
    return method(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/models.py", line 969, in _deploy
    autoscaling_target_accelerator_duty_cycle=autoscaling_target_accelerator_duty_cycle,
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/aiplatform/models.py", line 1169, in _deploy_call
    [autoscaling_metric_spec]
TypeError: Not a cmessage
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by entrpn** [comment]
Another datapoint. If I remove `machine_type` from the endpoint.deploy function call, which should allow for autoscaling resources, I get the same error.

**Comment by entrpn** [comment]
Closing this. The environment I was using got messed up somehow. This was using Theia IDE experimental notebooks. I created a new notebook and it works fine.
