### ISSUE TITLE
log_metrics() fails with strange error when called with empty dict

### ISSUE THREAD

**Issue by andrelynum** [googleapis/python-aiplatform#1674]
Version 1.16.1 and 1.17.0, python 3.7 and python 3.8 running in europe-west4

Running the following script:

```
import google.cloud.aiplatform as aip

aip.init(experiment='any-experiment')

with aip.start_run('new-run') as run:
    run.log_params({'fnark': 4})
    run.log_metrics({})
```

produces the following error:

```
Traceback (most recent call last):
  File "/project-path/venv/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/project-path/venv/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/project-path/venv/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.ABORTED
	details = "Specified Context `etag`: `1663335859173` does not match server `etag`: `1663335857654`"
	debug_error_string = "{"created":"@1663335860.714146000","description":"Error received from peer ipv4:XXX.XXX.XXX.XXX:443","file":"src/core/lib/surface/call.cc","file_line":906,"grpc_message":"Specified Context `etag`: `1663335859173` does not match server `etag`: `1663335857654`","grpc_status":10}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    run.log_metrics({})
  File "/project-path/venv/lib/python3.8/site-packages/google/cloud/aiplatform/metadata/experiment_run_resource.py", line 1060, in __exit__
    metadata._experiment_tracker.end_run(state=state)
  File "/project-path/venv/lib/python3.8/site-packages/google/cloud/aiplatform/metadata/metadata.py", line 327, in end_run
    self._experiment_run.end_run(state=state)
  File "/project-path/venv/lib/python3.8/site-packages/google/cloud/aiplatform/metadata/experiment_run_resource.py", line 1075, in end_run
    self.update_state(state)
  File "/project-path/venv/lib/python3.8/site-packages/google/cloud/aiplatform/metadata/experiment_run_resource.py", line 347, in update_state
    self._metadata_node.update(metadata={constants._STATE_KEY: state.name})
  File "/project-path/venv/lib/python3.8/site-packages/google/cloud/aiplatform/metadata/resource.py", line 307, in update
    update_gca_resource = self._update_resource(
  File "/project-path/venv/lib/python3.8/site-packages/google/cloud/aiplatform/metadata/context.py", line 274, in _update_resource
    return client.update_context(context=resource)
  File "/project-path/venv/lib/python3.8/site-packages/google/cloud/aiplatform_v1/services/metadata_service/client.py", line 2100, in update_context
    response = rpc(
  File "/project-path/venv/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/project-path/venv/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.Aborted: 409 Specified Context `etag`: `1663335859173` does not match server `etag`: `1663335857654`
```

**Comment by dss-nkraszewska** [comment]
Hi. I got the same error when I tried to run `log_metrics` method on resumed run:
```
aiplatform.init(experiment='my-experiment')
with aiplatform.start_run('my-run', resume=True) as my_run:
    my_run.log_params({'learning_rate':0.1})
```

**Comment by jaycee-li** [comment]
Hi @dss-nkraszewska , this bug should be fixed now. I'll close this issue. Feel free to re-open if you still get this bug. Thanks!

**Comment by dss-nkraszewska** [comment]
Hi, thank you, I appreciate it! :)
