### ISSUE TITLE
Pre-built containers for custom training: issues with tensorflow-io

### ISSUE THREAD

**Issue by hugoferrero** [googleapis/python-aiplatform#1732]
Hi. I'm using this image "us-docker.pkg.dev/vertex-ai/training/tf-cpu.2-9:latest" in "Custom training job" ( Vertex AI). I get the error printed below. I think the problem is the version of tensorflow-io, which is "0.23.1" and it's not compatible with the version of tensorflow image (2.9). However, the training job works totally fine with the image "us-docker.pkg.dev/vertex-ai/training/tf-cpu.2-7:latest" which has  compatible versions of tensorflow-io  (0.23.1) and tensorflow (2.7).
[Compatibility chart](https://github.com/tensorflow/io)
Error: 
```python
Training pipeline failed with error message: The replica workerpool0-0 exited with a non-zero status of 1. Traceback (most recent call last): File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/root/.local/lib/python3.7/site-packages/aiplatform_custom_trainer_script/task.py", line 25, in <module> bq_client = BigQueryClient() File "/root/.local/lib/python3.7/site-packages/tensorflow_io/python/ops/bigquery_dataset_ops.py", line 61, in __init__ self._client_resource = core_ops.io_big_query_client() File "/root/.local/lib/python3.7/site-packages/tensorflow_io/python/ops/__init__.py", line 88, in __getattr__ return getattr(self._load(), attrb) File "/root/.local/lib/python3.7/site-packages/tensorflow_io/python/ops/__init__.py", line 84, in _load self._mod = _load_library(self._library) File "/root/.local/lib/python3.7/site-packages/tensorflow_io/python/ops/__init__.py", line 71, in _load_library + f"{filename}, from paths: {filenames}\ncaused by: {errs}" NotImplementedError: unable to open file: libtensorflow_io.so, from paths: ['/root/.local/lib/python3.7/site-packages/tensorflow_io/python/ops/libtensorflow_io.so'] caused by: ['/root/.local/lib/python3.7/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZNK10tensorflow4data15DatasetOpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb']
```
Thanks in advance.

**Comment by nayaknishant** [comment]
Closing this issue as it seems like expected behavior.
