### ISSUE TITLE
Endpoint prediction GRPC error 

### ISSUE THREAD

**Issue by parthmishra** [googleapis/python-aiplatform#1849]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-aiplatform/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Ubuntu 20.04.5 LTS
  - Python version: 3.9.7
  - pip version: 22.3
  - `google-cloud-aiplatform` version: 1.19.1

#### Steps to reproduce

  1. Create Vertex Endpoint for custom trained model
  2. Send prediction request

#### Code example

```python
aiplatform.init(project="my-project", location="my-location")
endpoint = aiplatform.Endpoint("endpoint-id")
response = endpoint.predict(instances=[{...}, {...}, {...}], parameters={})
print(response.predictions) 
```

#### Stack trace
```
Traceback (most recent call last):
  File "/home/jupyter/.pyenv/versions/***/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/jupyter/.pyenv/versions/***/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/jupyter/.pyenv/versions/***/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Received RST_STREAM with error code 2"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:***:443 {grpc_message:"Received RST_STREAM with error code 2", grpc_status:13, created_time:"2022-12-13T18:05:21.914025462+00:00"}"
>



The above exception was the direct cause of the following exception:



Traceback (most recent call last):
  File "/home/jupyter/***/***-model/predict.py", line 12, in <module>
    predictions = endpoint.predict(instances=input_dict["instances"], parameters=input_dict["parameters"])
  File "/home/jupyter/.pyenv/versions/***/lib/python3.9/site-packages/google/cloud/aiplatform/models.py", line 1503, in predict
    prediction_response = self._prediction_client.predict(
  File "/home/jupyter/.pyenv/versions/***/lib/python3.9/site-packages/google/cloud/aiplatform_v1/services/prediction_service/client.py", line 589, in predict
    response = rpc(
  File "/home/jupyter/.pyenv/versions/***/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/jupyter/.pyenv/versions/***/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InternalServerError: 500 Received RST_STREAM with error code 2
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthmishra** [comment]
Did some further digging into the HTTP requests and I was able to replicate the issue with `gcloud` and `requests`. 

From what I can tell, this issue may be upstream with Vertex Endpoints service as it's adding a `Content-Encoding: gzip` header to responses even if they are actually uncompressed. I assume something similar is causing these GRPC errors?

**Comment by rosiezou** [comment]
@parthmishra I was unable to reproduce this using linux + python 3.9.7 + the latest version of the SDK. Can you double-check that the issue is still present when you upgrade to the latest version of the SDK? If yes, then I would recommend providing some more information about your input data (eg. sample input) so we could look into it more. Also, 500 indicates a server error, so I will be routing this issue to a different teammate who works on the backend code.

**Comment by rosiezou** [comment]
@kthytang please take a look.

**Comment by kthytang** [comment]
@parthmishra

To be able to investigate more deeply, we'll need:
1) your actual request body
2) project number/id
3) endpoint id

Feel free to send the above to cloudml-feedback@google.com if you're not comfortable sharing them here.

**Comment by parthmishra** [comment]
I can't give more details on my deployed model, but I was able to reproduce the exact issue by deploying a model using this notebook from the Vertex samples repo: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/ml_ops/stage2/get_started_vertex_training_r_using_r_kernel.ipynb

Our model is also a custom-trained R model that's very similar to the one in the notebook and the same issue occurs where hitting the Endpoint via curl works, but fails with the Python SDK (1.21.0) or against the API URL when using python requests library.

**Comment by gustavo-neoswap** [comment]
Any progress on this? 
Having the same issue
