### ISSUE TITLE
import error with shapely.geos

### ISSUE THREAD

**Issue by vnesh-san** [googleapis/python-aiplatform#1852]
during the import the aiplatform, I get the following error.

```
from google.cloud import aiplatform
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/aiplatform/__init__.py", line 24, in <module>
    from google.cloud.aiplatform import initializer
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/aiplatform/initializer.py", line 34, in <module>
    from google.cloud.aiplatform.metadata import metadata
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/aiplatform/metadata/metadata.py", line 25, in <module>
    from google.cloud.aiplatform import pipeline_jobs
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/aiplatform/pipeline_jobs.py", line 31, in <module>
    from google.cloud.aiplatform.metadata import artifact
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/aiplatform/metadata/artifact.py", line 25, in <module>
    from google.cloud.aiplatform import models
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/aiplatform/models.py", line 46, in <module>
    from google.cloud.aiplatform import jobs
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/aiplatform/jobs.py", line 26, in <module>
    from google.cloud import bigquery
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/bigquery/client.py", line 75, in <module>
    from google.cloud.bigquery.dataset import Dataset
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/bigquery/dataset.py", line 25, in <module>
    from google.cloud.bigquery.routine import RoutineReference
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/bigquery/routine/__init__.py", line 18, in <module>
    from google.cloud.bigquery.enums import DeterminismLevel
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/bigquery/enums.py", line 21, in <module>
    from google.cloud.bigquery.query import ScalarQueryParameterType
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/bigquery/query.py", line 23, in <module>
    from google.cloud.bigquery.table import _parse_schema_resource
  File "/home/vignesh/miniconda3/envs/the_new_age/lib/python3.10/site-packages/google/cloud/bigquery/table.py", line 44, in <module>
    _read_wkt = shapely.geos.WKTReader(shapely.geos.lgeos).read
AttributeError: module 'shapely.geos' has no attribute 'WKTReader'
```

google-cloud-aiplatform version 1.19.1

**Comment by davidcavazos** [comment]
Same happens with `google-cloud-aiplatform==1.20.0`. The issue is that `shapely` [just released version 2.0.0 on Dec 12](https://pypi.org/project/shapely/#history), and it's apparently not compatible with either aiplatform or bigquery.

# Steps to reproduce

In a clean virtual environment.

```sh
pip install -U google-cloud-aiplatform
```

In a Python script:

```py
from google.cloud import aiplatform
```

# Workaround

Pinning to the `shapely` latest version <2.0 as a constraint seems to fix it.

```sh
pip install -U google-cloud-aiplatform shapely==1.8.5
```

**Comment by davidcavazos** [comment]
Assigning as a P0 since it blocks people from installing the libraries, the fix should be pinning the `shapely` version constraint so it should be fairly straightforward.

**Comment by davidcavazos** [comment]
I was able to reproduce in Colab.

**Comment by davidcavazos** [comment]
Changing to P1 since it's not reproducible in local clean virtual environment, but it's reproducible in Colab. It's most likely a dependency conflict with a pre-installed package available in Colab.

**Comment by helinwang** [comment]
This is going to break a lot of Google's notebooks in colab. Can we prioritize the fix rollout? We are in RRC1:Guarded not in freeze yet.

**Comment by nayaknishant** [comment]
https://github.com/googleapis/python-aiplatform/commit/1efd81666ac63e1704322ad5771b3208a35bc479 has been pushed out. We are pinning `shapely < 2.0.0` to fix this error. Thanks for all the feedback and contribution!

**Comment by davidcavazos** [comment]
When is the next version including this patch expected to be published?

**Comment by nayaknishant** [comment]
Hey David, we plan to have a version release this week.

**Comment by AmineEchraibi** [comment]
Hello, after the downgrade of the shapely version I get this error: 
```python
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].
``` 
Could someone please help ? thanks

**Comment by jzxu** [comment]
Hi, has this issue been fixed? I just tried to run "pip install google-cloud-aiplatform" and it automatically reverted my installed shapely version to 1.8.5.post1. This is a blocker for my project as certain geopandas operations using shapely <2.0.0 is orders of magnitude slower than with shapely >=2.0.0.
