### ISSUE TITLE
AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'WhichOneof'

### ISSUE THREAD

**Issue by ianepjeong** [googleapis/python-aiplatform#1859]
I updated python-aiplatform today, and am running into the following issue:

```Traceback (most recent call last):
  File "predict.py", line 84, in <module>
    predict_using_vertexai(args)
  File "predict.py", line 46, in predict_using_vertexai
    detect_mounds(notProcessedImagePaths, client, endpoint, parameters, writer)
  File "predict.py", line 63, in detect_mounds
    response = client.predict(endpoint=endpoint, instances=instances, parameters=parameters)
  File "/home/ianjeong/.local/lib/python3.8/site-packages/google/cloud/aiplatform_v1/services/prediction_service/client.py", line 574, in predict
    request.instances.extend(instances)
  File "/software/python-anaconda-2020.11-el8-x86_64/lib/python3.8/site-packages/proto/message.py", line 752, in __getattr__
    return marshal.to_python(pb_type, pb_value, absent=key not in self)
  File "/software/python-anaconda-2020.11-el8-x86_64/lib/python3.8/site-packages/proto/marshal/marshal.py", line 180, in to_python
    return rule.to_python(value, absent=absent)
  File "/home/ianjeong/.local/lib/python3.8/site-packages/google/cloud/aiplatform/utils/enhanced_library/_decorators.py", line 24, in to_python
    return super().to_python(value, absent=absent)
  File "/software/python-anaconda-2020.11-el8-x86_64/lib/python3.8/site-packages/proto/marshal/rules/struct.py", line 39, in to_python
    kind = value.WhichOneof("kind")
AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'WhichOneof'
```

#### Environment details

  - OS type and version:
      Operating System: Red Hat Enterprise Linux 8.4 (Ootpa)
      CPE OS Name: cpe:/o:redhat:enterprise_linux:8.4:GA
      Kernel: Linux 4.18.0-305.57.1.el8_4.x86_64
      Architecture: x86-64
  - Python version: Python 3.8.5
  - pip version: pip 22.3.1
  - `google-cloud-aiplatform` version: 
`
Name: google-cloud-aiplatform
Version: 1.20.0
Summary: Vertex AI API client library
Home-page: https://github.com/googleapis/python-aiplatform
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /home/ianjeong/.local/lib/python3.8/site-packages
Requires: google-api-core, google-cloud-bigquery, google-cloud-resource-manager, google-cloud-storage, packaging, proto-plus, protobuf
`

Below is the list of the google-cloud related libraries in my environment:
`Package                            Version
---------------------------------- --------------------
google-api-core                    1.34.0
google-api-python-client           1.12.11
google-auth                        2.6.0
google-auth-httplib2               0.1.0
google-auth-oauthlib               0.4.4
google-cloud                       0.34.0
google-cloud-aiplatform            1.20.0
google-cloud-automl                2.5.0
google-cloud-bigquery              2.29.0
google-cloud-core                  2.3.0
google-cloud-resource-manager      1.6.3
google-cloud-storage               1.43.0
google-cloud-vision                3.1.4
google-crc32c                      1.3.0
google-pasta                       0.2.0
google-resumable-media             2.1.0
googleapis-common-protos           1.56.4
googledrivedownloader              0.4'

#### Steps to reproduce

  1. ?
  2. ?

#### Code example
this is essentially how I am using the libray:
```python

from google.cloud import aiplatform
from google.cloud.aiplatform.gapic.schema import predict

location: str = "us-central1",
api_endpoint: str = "us-central1-aiplatform.googleapis.com"
client_options = {"api_endpoint": api_endpoint}            #api_endpoint gets passed in when I run the python file
client = aiplatform.gapic.PredictionServiceClient(client_options=client_options)
parameters = predict.params.ImageObjectDetectionPredictionParams(
    confidence_threshold=0.5, max_predictions=20,
).to_value()
endpoint = client.endpoint_path(
    project=args.project, location=location, endpoint=args.endpoint_id
)

with open(imagePath, 'rb') as ff:                #imagePath is the path to an image 
    content = ff.read()
    encoded_content = base64.b64encode(content).decode("utf-8")
    instance = predict.instance.ImageObjectDetectionPredictionInstance(
        content=encoded_content,
    ).to_value()
    instances = [instance]
response = client.predict(endpoint=endpoint, instances=instances, parameters=parameters)
```
Please help me debug this!

Thanks!

**Comment by ianepjeong** [comment]
Never mind! I was able to resolve the issues after updating:

- google-cloud-core
- google-api-core
- protobuf

for those who may run into the same issues, here is the list of modules:
```
Package                            Version
---------------------------------- --------------------
google-api-core                    2.11.0
google-api-python-client           1.12.11
google-auth                        2.15.0
google-auth-httplib2               0.1.0
google-auth-oauthlib               0.4.4
google-cloud                       0.34.0
google-cloud-aiplatform            1.20.0
google-cloud-automl                2.5.0
google-cloud-bigquery              2.29.0
google-cloud-core                  2.3.2
google-cloud-resource-manager      1.6.3
google-cloud-storage               1.43.0
google-cloud-vision                3.1.4
google-crc32c                      1.3.0
google-pasta                       0.2.0
google-resumable-media             2.1.0
googleapis-common-protos           1.56.4
googledrivedownloader              0.4
grpc-google-iam-v1                 0.12.4
grpcio                             1.51.1
grpcio-status                      1.48.2
packaging                          21.3
proto-plus                         1.22.1
protobuf                           4.21.12
```
