### ISSUE TITLE
No accelerator compatible

### ISSUE THREAD

**Issue by Davidnet** [googleapis/python-aiplatform#1922]
Hi everyone I am trying to get a vertex ai job but I never been able to get the good combination of machine-type and accelerator

#### Environment details

  - OS type and version: Fedora 37
  - Python version: `3.10.8`
  - pip version: `22.3.1`
  - `google-cloud-aiplatform` version:
  ```
Name: google-cloud-aiplatform
Version: 1.14.0
Summary: Vertex AI API client library
Home-page: https://github.com/googleapis/python-aiplatform
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /home/dgromov/Documents/updata.ca/training-vertex/.venv/lib/python3.10/site-packages
Requires: google-api-core, google-cloud-bigquery, google-cloud-resource-manager, google-cloud-storage, packaging, proto-plus, protobuf
Required-by: google-cloud-pipeline-components
```

#### Steps to reproduce

  1. python custom_job.py # See below:
  

#### Code example

```python
from google.cloud import aiplatform

from google.oauth2.credentials import Credentials

creds = Credentials("CENSORED")

worker_pool_specs = [
    {
        "machine_spec": {
            "machine_type": "e2-standard-8",
            "accelerator_type": aiplatform.gapic.AcceleratorType.NVIDIA_TESLA_K80,
            "accelerator_count": 1,
        },
        "replica_count": 1,
        "container_spec": {
            "image_uri": "tensorflow/tensorflow:latest-gpu",
            "command": ["sh", "-c"],
            "args": ["nvidia-smi"],
        },
    }
]

aiplatform.init(
    project="censored",
    credentials=creds,
    staging_bucket="gs://CENSORED",
)

my_job = aiplatform.CustomJob(
    display_name="my_job",
    worker_pool_specs=worker_pool_specs,
    labels={"my_key": "my_value"},
    project="CENSORED",
    location="northamerica-northeast1",
)

my_job.run()

```

#### Stack trace
```
Traceback (most recent call last):
  File "/home/dgromov/Documents/updata.ca/training-vertex/.venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/dgromov/Documents/updata.ca/training-vertex/.venv/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/dgromov/Documents/updata.ca/training-vertex/.venv/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Accelerator "NVIDIA_TESLA_K80" is not supported for machine type "e2-standard-4""
        debug_error_string = "UNKNOWN:Error received from peer ipv4:172.217.13.202:443 {created_time:"2023-01-25T16:12:11.771543182-05:00", grpc_status:3, grpc_message:"Accelerator \"NVIDIA_TESLA_K80\" is not supported for machine type \"e2-standard-4\""}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dgromov/Documents/updata.ca/training-vertex/pipelinev2.py", line 39, in <module>
    my_job.run()
  File "/home/dgromov/Documents/updata.ca/training-vertex/.venv/lib/python3.10/site-packages/google/cloud/aiplatform/base.py", line 750, in wrapper
    return method(*args, **kwargs)
  File "/home/dgromov/Documents/updata.ca/training-vertex/.venv/lib/python3.10/site-packages/google/cloud/aiplatform/jobs.py", line 1495, in run
    self._gca_resource = self.api_client.create_custom_job(
  File "/home/dgromov/Documents/updata.ca/training-vertex/.venv/lib/python3.10/site-packages/google/cloud/aiplatform_v1/services/job_service/client.py", line 790, in create_custom_job
    response = rpc(
  File "/home/dgromov/Documents/updata.ca/training-vertex/.venv/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/dgromov/Documents/updata.ca/training-vertex/.venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Accelerator "NVIDIA_TESLA_K80" is not supported for machine type "e2-standard-4"
```

I have tried every combination and never able to work, can you help me out?

Thanks!

**Comment by matthew29tang** [comment]
Compatible machines for various accelerators can be found in the documentation [here](https://cloud.google.com/vertex-ai/docs/training/configure-compute). For example, the machine type `n1-standard-4` would be compatible with the accelerator `NVIDIA_TESLA_K80`.
