### ISSUE TITLE
grpc Internal error while creating create_batch_prediction_job using custom container 

### ISSUE THREAD

**Issue by janmejaya-nanda** [googleapis/python-aiplatform#2051]
#### Environment details

  - OS type and version: ubuntu 16.04
  - Python version: 3.7.5
  - pip version: 21.3.1
  - `google-cloud-aiplatform` version: 1.22.0

#### Steps to reproduce

I am using [create_batch_prediction_job](https://github.com/googleapis/python-aiplatform/blob/main/samples/snippets/job_service/create_batch_prediction_job_bigquery_sample.py) with custom container using `unmanaged_container_model`. while creating the batch prediction job it failed with an Internal error.

#### Code example

```
batch_prediction_job_dict = {
        "display_name": display_name,
        "unmanaged_container_model": {
            "artifact_uri": "gs://atrifact_path",
            # "predict_schemata": {
            #   "instanceSchemaUri": '',
            #   "parametersSchemaUri": '',
            #   "predictionSchemaUri": ""
            # },
            "container_spec": {
                "image_uri": "us-central1-docker.pkg.dev/project/repo/image:latest",
                # "command": [],
                # "args": [],
                "env": [
                        {"name": "BQ_URI", "value": "bq://sample.bq.url"}
                ],
                "ports": [{"container_port": 8080}],
                "predict_route": "/predict",
                "health_route": "/health"
}
        },
        "input_config": {"instances_format": 'jsonl', "gcs_source": {"uris": []}},
        "output_config": {
                    "predictions_format": 'jsonl',
                    "gcs_destination": {"output_uri_prefix": PIPELINE_ROOT_STORAGE},
                },
        "dedicated_resources": {
            "machine_spec": {
                "machine_type": "n1-standard-16",
                "accelerator_type": aiplatform.gapic.AcceleratorType.NVIDIA_TESLA_K80,
                "accelerator_count": 2,
            },
            "starting_replica_count": 1,
            "max_replica_count": 1,
        },
        "output_info": {"gcs_output_directory": PIPELINE_ROOT_STORAGE}
    }
   
    batch_prediction_job = gca_batch_prediction_job.BatchPredictionJob(**batch_prediction_job_dict)

    parent = f"projects/{PROJECT_ID}/locations/{REGION}"
    response = client.create_batch_prediction_job(
        parent=parent, batch_prediction_job=batch_prediction_job
    )
```

#### Stack trace
```
Traceback (most recent call last):
  File "/home/user/.virtualenv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/user/.virtualenv/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/user/.virtualenv/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Internal error encountered."
        debug_error_string = "UNKNOWN:Error received from peer ipv6:------ {created_time:"2023-03-29T19:07:55.202536314+05:30", grpc_status:13, grpc_message:"Internal error encountered."}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kubeflow_inference_pipeline_dsl.py", line 104, in <module>
    create_batch_prediction_job_sample()
  File "kubeflow_inference_pipeline_dsl.py", line 98, in create_batch_prediction_job_sample
    parent=parent, batch_prediction_job=batch_prediction_job
  File "/home/user/.virtualenv/lib/python3.7/site-packages/google/cloud/aiplatform_v1/services/job_service/client.py", line 3389, in create_batch_prediction_job
    metadata=metadata,
  File "/home/user/.virtualenv/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/user/.virtualenv/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InternalServerError: 500 Internal error encountered
```

**Comment by sararob** [comment]
If you go to the GCS output directory for your Batch Prediction job, are there any additional error messages in the prediction output files?

**Comment by janmejaya-nanda** [comment]
@sararob I am not seeing any additional files in my `gcs_output_directory`.

**Comment by sararob** [comment]
Are you still running into this 500 error?

**Comment by matthew29tang** [comment]
Closing this thread due to inactivity. If the issue persists, feel free to re-open.

**Comment by andreskull** [comment]
I experience the same error starting from 28.2.2025. Before the same code worked.

An unexpected error occurred:
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/grpc/_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
                             ^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/grpc/_interceptor.py", line 332, in _with_call
    return call.result(), call
           ^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/grpc/_channel.py", line 440, in result
    raise self
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/grpc/_interceptor.py", line 315, in continuation
    response, call = self._thunk(new_method).with_call(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/grpc/_channel.py", line 1198, in with_call
    return _end_unary_response_blocking(state, call, True, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "Internal error encountered."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:64.233.164.95:443 {grpc_message:"Internal error encountered.", grpc_status:13, created_time:"2025-03-03T01:24:18.94338734+00:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/batch_creator.py", line 187, in generic_batch_creator
    message, _ = create_batches(config, max_batches, max_rows_per_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/batch_creator.py", line 153, in create_batches
    batch_id = create_batch(batch_df, config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/batch_creator.py", line 45, in create_batch
    job = BatchPredictionJob.submit(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/vertexai/batch_prediction/_batch_prediction.py", line 215, in submit
    aiplatform_job = jobs.BatchPredictionJob.submit(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/cloud/aiplatform/jobs.py", line 878, in submit
    return cls._submit_impl(
           ^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/cloud/aiplatform/jobs.py", line 1337, in _submit_impl
    return cls._submit_and_optionally_wait_with_sync_support(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/cloud/aiplatform/base.py", line 863, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/cloud/aiplatform/jobs.py", line 1406, in _submit_and_optionally_wait_with_sync_support
    gca_batch_prediction_job = api_client.create_batch_prediction_job(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/cloud/aiplatform_v1/services/job_service/client.py", line 3827, in create_batch_prediction_job
    response = rpc(
               ^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InternalServerError: 500 Internal error encountered.

**Comment by Vishwa36** [comment]
Did you find a way to resolve this internal error?

**Comment by andreskull** [comment]
> Did you find a way to resolve this internal error?

No, it still persists. I hoped that Google engineers will fix it on Monday but seems this is not the case. I do not know how to escalate it elsewhere than here.
