### ISSUE TITLE
Pydantic error while calling autolog functionality for Vertex AI Experiments

### ISSUE THREAD

**Issue by wesselhuising** [googleapis/python-aiplatform#2525]
#### Environment details

  - OS type and version: Debian 10
  - Python version:  Python 3.10.12
  - pip version: 23.21
  - `google-cloud-aiplatform` version:  1.31.1

#### Steps to reproduce

  1. Use Pydantic over version 2.x.x
  2. Call `aiplatform.autolog()`

#### Code example

```python
        aiplatform.init(
            experiment=experiment_name,
            experiment_description=experiment_description,
            experiment_tensorboard=experiment_tensorboard,
            project=project,
            location=location,
        )

        aiplatform.autolog()

        aiplatform.autolog(disable=True)
```

#### Stack trace
```
Traceback (most recent call last):

  File "project/src/project/training/train.py", line 28, in train
    with Experiment(

  File "project/src/project/training/train.py", line 38, in __enter__
    aiplatform.autolog()

  File "/home/jupyter/.cache/pypoetry/virtualenvs/venv/lib/python3.10/site-packages/google/cloud/aiplatform/metadata/metadata.py", line 492, in autolog
    import mlflow

  File "/home/jupyter/.cache/pypoetry/virtualenvs/venv/lib/python3.10/site-packages/mlflow/__init__.py", line 247, in <module>
    from mlflow import gateway  # noqa: F401

  File "/home/jupyter/.cache/pypoetry/virtualenvs/venv/lib/python3.10/site-packages/mlflow/gateway/__init__.py", line 1, in <module>
    from mlflow.gateway.fluent import get_route, search_routes, query, create_route, delete_route

  File "/home/jupyter/.cache/pypoetry/virtualenvs/venv/lib/python3.10/site-packages/mlflow/gateway/fluent.py", line 4, in <module>
    from mlflow.gateway.client import MlflowGatewayClient

  File "/home/jupyter/.cache/pypoetry/virtualenvs/venv/lib/python3.10/site-packages/mlflow/gateway/client.py", line 8, in <module>
    from mlflow.gateway.config import Route

  File "/home/jupyter/.cache/pypoetry/virtualenvs/venv/lib/python3.10/site-packages/mlflow/gateway/config.py", line 66, in <module>
    class OpenAIConfig(ConfigModel):

  File "/home/jupyter/.cache/pypoetry/virtualenvs/venv/lib/python3.10/site-packages/mlflow/gateway/config.py", line 79, in OpenAIConfig
    @root_validator(pre=False)

  File "/home/jupyter/.cache/pypoetry/virtualenvs/venv/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(

pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.

For further information visit https://errors.pydantic.dev/2.3/u/root-validator-pre-skip
```

I guess it problem arises when using pydantic v2 over v1.

**Comment by matthew29tang** [comment]
I have no errors running your example code snippet in colab using `pydantic==2.2.1` and `mlflow==2.1.1`. What version of `mlflow` do you have? It looks like the error is coming from `import mlflow` - if you run that separately without aiplatform, does that cause the same error?

Perhaps this is related: https://github.com/mlflow/mlflow/issues/9331

**Comment by matthew29tang** [comment]
Closing this issue due to inactivity. If there is still an issue related to Vertex SDK, feel free to re-open.
