### ISSUE TITLE
`from google.cloud import aiplatform` fails in Python 3.8

### ISSUE THREAD

**Issue by JoeStrout** [googleapis/python-aiplatform#2792]
I get a traceback ending in:
```
  File "/Users/jstrout/opt/anaconda3/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/jstrout/opt/anaconda3/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'
```

I have been working around this by using pyenv to force Python 3.7 in my google.cloud projects.  But this morning, I got:

```
WARNING:  Python 3.7.x is no longer officially supported by the Google Cloud CLI
and may not function correctly. Please use Python version 3.8 and up.
```

So we're told to use Python version 3.8, yet that does not actually appear to work (while 3.7 still does).

#### Environment details

  - OS type and version: MacOS 13.4.1
  - Python version: 3.8.8
  - pip version: 23.0.1
  - `google-cloud-aiplatform` version: 1.25.0
 
#### Steps to reproduce

  1. run Python 3.8.8 (probably applies to other versions >= 3.8, but this is what I've tried)
  2. `from google.cloud import aiplatform`

#### Code example

```python
from google.cloud import aiplatform
```

#### Stack trace
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jstrout/opt/anaconda3/lib/python3.8/site-packages/google/cloud/aiplatform/__init__.py", line 24, in <module>
    from google.cloud.aiplatform import initializer
  File "/Users/jstrout/opt/anaconda3/lib/python3.8/site-packages/google/cloud/aiplatform/initializer.py", line 26, in <module>
    from google.api_core import gapic_v1
  File "/Users/jstrout/opt/anaconda3/lib/python3.8/site-packages/google/api_core/gapic_v1/__init__.py", line 16, in <module>
    from google.api_core.gapic_v1 import config
  File "/Users/jstrout/opt/anaconda3/lib/python3.8/site-packages/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
  File "/Users/jstrout/opt/anaconda3/lib/python3.8/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/jstrout/opt/anaconda3/lib/python3.8/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/jstrout/opt/anaconda3/lib/python3.8/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_kCFStreamPropertySocketNativeHandle'
```

**Comment by sasha-gitg** [comment]
Please provide the version of grpc in the environment.
