### ISSUE TITLE
"SklearnEstimator = sklearn.base.BaseEstimator" AttributeError: module 'sklearn' has no attribute 'base

### ISSUE THREAD

**Issue by turnham** [googleapis/python-aiplatform#2811]
#### Environment details

- OS type and version: Mac M1
- Python version: 3.9.14
- pip version: 22.0.4
- google-cloud-aiplatform version: 1.35.0

#### Steps to reproduce

1. Fresh system (no python packages installed)
2. pip install google-cloud-aiplatform
3. ```python test.py``` with this one-line file:
```python
from vertexai.preview.language_models import TextGenerationModel
```
First exception:
```
> python test.py
Traceback (most recent call last):
  File "/Users/turnham/opensource/llmware/test.py", line 1, in <module>
    from vertexai.preview.language_models import TextGenerationModel
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/vertexai/__init__.py", line 17, in <module>
    from google.cloud.aiplatform import init
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/aiplatform/__init__.py", line 24, in <module>
    from google.cloud.aiplatform import initializer
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/aiplatform/initializer.py", line 36, in <module>
    from google.cloud.aiplatform.metadata import metadata
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/aiplatform/metadata/metadata.py", line 28, in <module>
    from google.cloud.aiplatform import pipeline_jobs
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/aiplatform/pipeline_jobs.py", line 31, in <module>
    from google.cloud.aiplatform.metadata import artifact
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/aiplatform/metadata/artifact.py", line 26, in <module>
    from google.cloud.aiplatform import models
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/aiplatform/models.py", line 47, in <module>
    from google.cloud.aiplatform import jobs
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/aiplatform/jobs.py", line 28, in <module>
    from google.cloud import bigquery
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 76, in <module>
    from google.cloud.bigquery import _job_helpers
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/bigquery/_job_helpers.py", line 24, in <module>
    from google.cloud.bigquery import job
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/bigquery/job/__init__.py", line 27, in <module>
    from google.cloud.bigquery.job.copy_ import CopyJob
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/bigquery/job/copy_.py", line 22, in <module>
    from google.cloud.bigquery.table import TableReference
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/bigquery/table.py", line 62, in <module>
    from google.cloud.bigquery import _pandas_helpers
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 74, in <module>
    _to_wkb = _to_wkb()
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 67, in _to_wkb
    notnull = pandas.notnull
AttributeError: module 'pandas' has no attribute 'notnull'
```
4. Fix with ```pip install pandas```
5. Then do another ```python test.py```

Next exception:
```
> python test.py
Traceback (most recent call last):
  File "/Users/turnham/opensource/llmware/test.py", line 1, in <module>
    from vertexai.preview.language_models import TextGenerationModel
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/vertexai/__init__.py", line 18, in <module>
    from vertexai import preview
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/vertexai/preview/__init__.py", line 20, in <module>
    from vertexai.preview import developer
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/vertexai/preview/developer/__init__.py", line 18, in <module>
    from vertexai.preview._workflow.serialization_engine import (
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/vertexai/preview/_workflow/serialization_engine/any_serializer.py", line 24, in <module>
    from vertexai.preview._workflow.serialization_engine import (
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/vertexai/preview/_workflow/serialization_engine/serializers.py", line 37, in <module>
    from vertexai.preview._workflow.serialization_engine import (
  File "/Users/turnham/.pyenv/versions/3.9.14/lib/python3.9/site-packages/vertexai/preview/_workflow/serialization_engine/serializers_base.py", line 60, in <module>
    SklearnEstimator = sklearn.base.BaseEstimator
AttributeError: module 'sklearn' has no attribute 'base'
```
This is fixed with ```pip install scikit-learn```

This latest sklearn issue seems relatively new or at least we hadn't seen last month and we only found it now when doing some clean system testing. 

It looks like scikit-learn is only included in the "testing" (testing_extra_require) list in setup.py.  Is that by design?  Should we be installing with ["testing"] if we are using: vertexai.preview.* ?

**Comment by jaycee-li** [comment]
Fixed in https://github.com/googleapis/python-aiplatform/commit/8e42bc5e97d7f74a7ccba059be8327c61a342391
