### ISSUE TITLE
Vertex AI SDK - Proxy with Authentication does not work

### ISSUE THREAD

**Issue by nicola-alessi-reply** [googleapis/python-aiplatform#3040]
#### Environment details
Docker image: registry.redhat.io/ubi8/python-39
OS: Red Hat Enterprise Linux 8.8 (Ootpa)
python version: Python 3.9.16
pip version: pip 22.2.2
google-cloud-aiplatform:  1.35.0 (same error with latest version 1.35.4)
  

#### Steps to reproduce

  1. set the environment variable htts_proxy using authentication like 'username:password@proxy_uri:port'
  2. make a request to a LLM model.

#### Code example

```python
        os.environ['https_proxy'] = 'http://username:password@proxy_uri:port'
        vertexai.init(project="xxxxx", location="europe-west3")
        parameters = {
            "candidate_count": 1,
            "max_output_tokens": 1024,
            "temperature": 0,
            "top_p": 0.8,
            "top_k": 40
        }
        model = TextGenerationModel.from_pretrained("text-bison")
        response = model.predict(
            """hello""",
            **parameters
        )
        print(f"Response from Model: {response.text}")

```

#### Stack trace
```
  File "/opt/app-root/lib64/python3.9/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/app-root/lib64/python3.9/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed for username:password: C-ares status is not ARES_SUCCESS qtype=A name=username is_balancer=0: Domain name not found"
        debug_error_string = "UNKNOWN:DNS resolution failed for username:passowrd C-ares status is not ARES_SUCCESS qtype=A name=username is_balancer=0: Domain name not found {created_time:"2023-11-27T09:51:54.796217565+00:00", grpc_status:14}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/google/api_core/retry.py", line 207, in retry_target
    result = target()
  File "/opt/app-root/lib64/python3.9/site-packages/google/api_core/grpc_helpers.py", line 77, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ServiceUnavailable: 503 DNS resolution failed for username:password C-ares status is not ARES_SUCCESS qtype=A name=username is_balancer=0: Domain name not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app-root/src/src/genai_test_predict.py", line 52, in predict_example
    model = TextGenerationModel.from_pretrained("text-bison")
  File "/opt/app-root/lib64/python3.9/site-packages/vertexai/_model_garden/_model_garden_models.py", line 316, in from_pretrained
    return _from_pretrained(interface_class=cls, model_name=model_name)
  File "/opt/app-root/lib64/python3.9/site-packages/vertexai/_model_garden/_model_garden_models.py", line 218, in _from_pretrained
    model_info = _get_model_info(
  File "/opt/app-root/lib64/python3.9/site-packages/vertexai/_model_garden/_model_garden_models.py", line 134, in _get_model_info
    _publisher_models._PublisherModel(  # pylint: disable=protected-access
  File "/opt/app-root/lib64/python3.9/site-packages/google/cloud/aiplatform/_publisher_models.py", line 77, in __init__
    self._gca_resource = getattr(self.api_client, self._getter_method)(
  File "/opt/app-root/lib64/python3.9/site-packages/google/cloud/aiplatform_v1/services/model_garden_service/client.py", line 536, in get_publisher_model
    response = rpc(
  File "/opt/app-root/lib64/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/google/api_core/retry.py", line 372, in retry_wrapped_func
    return retry_target(
  File "/opt/app-root/lib64/python3.9/site-packages/google/api_core/retry.py", line 226, in retry_target
    raise exceptions.RetryError(
google.api_core.exceptions.RetryError: Deadline of 120.0s exceeded while calling target function, last exception: 503 DNS resolution failed for username:password C-ares status is not ARES_SUCCESS qtype=A name=username is_balancer=0: Domain name not found

Traceback (most recent call last):
  File "/opt/app-root/src/src/genai_test_predict.py", line 66, in <module>
    predict_example()
  File "/opt/app-root/src/src/genai_test_predict.py", line 62, in predict_example
    return response.text
```

#### Additional considerations:
- it works if I set https_proxy to a proxy that does not require authentication.
- As expected, If using a proxy that requires authentication, I get error 407 removing username and password from the environment variable.
- it looks like connecting to a proxy with authentication is not supported, then the library tries to perform a DNS resolution using username and password as URI.
- we would consider to use any workaround that does not require to install additional components to the docker image. 

Thank you very much

**Comment by nicola-alessi-reply** [comment]
we found a solution, I share it to help other people in the same situation.
It was not a bug of the library, the issue was related to a special characters in the password.
We have replaced all special characters with the escaped ones and now it is working.



 the password con
