### ISSUE TITLE
ModuleNotFoundError: No module named tensorboard.uploader

### ISSUE THREAD

**Issue by niraj06** [googleapis/python-aiplatform#3638]
We want to use cloud profiler in vertex ai
Followed instructions here https://cloud.google.com/vertex-ai/docs/training/tensorboard-profiler

Installed pip install "google-cloud-aiplatform[cloud_profiler]" version 1.48.0

when importing from google.cloud.aiplatform.training_utils import cloud_profiler
complaining tensorboard.uploader module not found

------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/userx/.pyenv/versions/pco-model-apps-nba-profile/lib/python3.10/site-packages/google/cloud/aiplatform/training_utils/cloud_profiler/__init__.py", line 18, in <module>
    from google.cloud.aiplatform.training_utils.cloud_profiler import initializer
  File "/Users/userx/.pyenv/versions/pco-model-apps-nba-profile/lib/python3.10/site-packages/google/cloud/aiplatform/training_utils/cloud_profiler/initializer.py", line 33, in <module>
    from google.cloud.aiplatform.training_utils.cloud_profiler.plugins.tensorflow import (
  File "/Users/userx/.pyenv/versions/pco-model-apps-nba-profile/lib/python3.10/site-packages/google/cloud/aiplatform/training_utils/cloud_profiler/plugins/tensorflow/tf_profiler.py", line 43, in <module>
    from google.cloud.aiplatform.tensorboard.plugins.tf_profiler import (
  File "/Users/userx/.pyenv/versions/pco-model-apps-nba-profile/lib/python3.10/site-packages/google/cloud/aiplatform/tensorboard/plugins/tf_profiler/profile_uploader.py", line 25, in <module>
    from tensorboard.uploader.proto import server_info_pb2
ModuleNotFoundError: No module named 'tensorboard.uploader'

**Comment by niraj06** [comment]
Observation: When we use tensorboard==2.15.1 it works fine, but with  tensorboard==2.16.1 its throws ModuleNotFoundError: No module named 'tensorboard.uploader'

**Comment by lakeyk** [comment]
This issue should be resolved with sdk version 1.49.0
