### ISSUE TITLE
Lists not supported in response_schema field in GenerationConfig

### ISSUE THREAD

**Issue by Krish120003** [googleapis/python-aiplatform#3853]
#### Environment details

  - Windows 11
  - Python version: 3.12.3
  - pip version: pip 24.0 
  - `google-cloud-aiplatform` version: 1.53.0

#### Steps to reproduce

  1. Setup a schema using Pydantic that uses lists
  2. Expect that schema as the response_schema when using response_mine_type = "application/json" in the GenerationConfig.

#### Code example

```python
from typing import List
from pydantic import BaseModel
from vertexai.preview.generative_models import (
    GenerativeModel,
    GenerationConfig,
)

from pprint import pprint
import json

model = GenerativeModel(model_name="gemini-1.5-pro")


class Recipe(BaseModel):
    recipe_name: str
    steps: List[str]


class RecipeBook(BaseModel):
    recipies: List[Recipe]

    
config = GenerationConfig(
    response_mime_type="application/json",
    response_schema=RecipeBook.model_json_schema(),
)

result = model.generate_content(
    "List 3 popular cookie recipes",
    generation_config=config,
)

pprint(json.loads(result.text))
```

#### Stack trace
```
Traceback (most recent call last):
  File "c:\Users\krish\Documents\GitHub\gemeni-testing\gen.py", line 23, in <module>
    config = GenerationConfig(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\krish\.virtualenvs\gemeni-testing-Afsr7j_1\Lib\site-packages\vertexai\generative_models\_generative_models.py", line 1242, in __init__
    raw_schema = aiplatform_types.Schema(gapic_schema_dict)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krish\.virtualenvs\gemeni-testing-Afsr7j_1\Lib\site-packages\proto\message.py", line 576, in __init__
    raise ValueError(
ValueError: Unknown field for Schema: $defs
```

**Comment by ZhenyiQ** [comment]
Thanks @Krish120003 for raising this! From the error message it looks like that the problem is due to nested BaseModel, which results in a key `$defs` (and later "$ref") in the return value of `RecipeBook.model_json_schema()`. This key does not conform to the openapi Schema (https://github.com/googleapis/python-aiplatform/blob/88c6a6a4f11285d429c3777f59101e53e4672185/google/cloud/aiplatform_v1/types/openapi.py#L63).

**Comment by krish-bell** [comment]
What would be the correct way to do this then?

**Comment by ZhenyiQ** [comment]
I think you'll need to add postprocessing for the return value of `Recipe book.model_json_schema()`, to replace the reference by the actual definition of `Recipe`, if pydantic doesn't support this off-the-shelf (AFAIK, it doesn't).

**Comment by krish-bell** [comment]
Is there a better method to achieve this if not using Pydantic?

**Comment by ZhenyiQ** [comment]
This seems to work: https://github.com/pydantic/pydantic/issues/889#issuecomment-850312496

For your code, it looks like
```
def replace_value_in_dict(item, original_schema):
    if isinstance(item, list):
        return [replace_value_in_dict(i, original_schema) for i in item]
    elif isinstance(item, dict):
        if list(item.keys()) == ['$ref']:
            definitions = item['$ref'][2:].split('/')
            res = original_schema.copy()
            for definition in definitions:
                res = res[definition]
            return res
        else:
            return { key: replace_value_in_dict(i, original_schema) for key, i in item.items()}
    else:
        return item


def main():
  recipies_schema = RecipeBook.model_json_schema()
  recipies_schema = replace_value_in_dict(recipies_schema.copy(), recipies_schema.copy())
  del recipies_schema['$defs']


  config = GenerationConfig(
      response_mime_type="application/json",
      response_schema=recipies_schema,
  )

  model = GenerativeModel("gemini-1.5-pro")
  response = model.generate_content(
      "List 3 popular cookie recipers",
      generation_config=config,
  )
```
