### ISSUE TITLE
Resource Exhausted error in deleting ragfile vertexai.preview.rag.delete_file

### ISSUE THREAD

**Issue by kunj-gandhi12** [googleapis/python-aiplatform#4338]
Hi, In vertex AI RAG service, when i am trying to delete more than 50-60 files within minute, then it showing the following error

```bash
Traceback (most recent call last):
  File "/home/kunj/project/.venv/lib/python3.12/site-packages/vertexai/preview/rag/rag_data.py", line 517, in delete_file
    client.delete_rag_file(request=request)
  File "/home/kunj/project/.venv/lib/python3.12/site-packages/google/cloud/aiplatform_v1beta1/services/vertex_rag_data_service/client.py", line 1852, in delete_rag_file
    response = rpc(
               ^^^^
  File "/home/kunj/project/.venv/lib/python3.12/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kunj/project/.venv/lib/python3.12/site-packages/google/api_core/grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.ResourceExhausted: 429 Quota exceeded for quota metric 'VertexRagDataService requests' and limit 'VertexRagDataService requests per minute per region' of service 'aiplatform.googleapis.com' for consumer 'project_number:567517593290'. [reason: "RATE_LIMIT_EXCEEDED"
domain: "googleapis.com"
metadata {
  key: "service"
  value: "aiplatform.googleapis.com"
}
metadata {
  key: "quota_metric"
  value: "aiplatform.googleapis.com/vertex_rag_data_requests"
}
metadata {
  key: "quota_location"
  value: "us-central1"
}
metadata {
  key: "quota_limit"
  value: "VertexRagDataRequestPerMinutePerProjectPerRegion"
}
metadata {
  key: "quota_limit_value"
  value: "60"
}
metadata {
  key: "consumer"
  value: "projects/567517593290"
}
, links {
  description: "Request a higher quota limit."
  url: "https://cloud.google.com/docs/quotas/help/request_increase"
}
]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kunj/.pyenv/versions/3.12.3/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home/kunj/.pyenv/versions/3.12.3/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kunj/project/check.py", line 72, in delete_files
    rag.delete_file(file, corpus_name)
  File "/home/kunj/project/.venv/lib/python3.12/site-packages/vertexai/preview/rag/rag_data.py", line 520, in delete_file
    raise RuntimeError("Failed in RagFile deletion due to: ", e) from e
RuntimeError: ('Failed in RagFile deletion due to: ', ResourceExhausted("Quota exceeded for quota metric 'VertexRagDataService requests' and limit 'VertexRagDataService requests per minute per region' of service 'aiplatform.googleapis.com' for consumer 'project_number:567517593290'."))
```

Module: `vertexai.preview.rag`
Method: `vertexai.preview.rag.delete_file`

Sample Code Block:

```python
from vertexai.preview import rag
import threading

corpus_name = "###"

files = list(rag.list_files(corpus_name=corpus_name))
file_names = [file.name for file in files]

# create batches of 10
batches = [file_names[i:i+10] for i in range(0, len(file_names), 10)]

def delete_files(batch, corpus_name):
    for file in batch:
        rag.delete_file(file, corpus_name)

# create threads
threads = []
for batch in batches:
    t = threading.Thread(target=delete_files, args=(batch, corpus_name))
    threads.append(t)
    t.start()

# wait for all threads to finish
for t in threads:
    t.join()
```

It is causing a unnecessary issue, as well i couldn't find any way to increase the quota in `Quota & System Limits Page`. Kindly help in resolving this issue.

**Comment by kunj-gandhi12** [comment]
This issue isn't limited to the delete_file API; it also affects the list_files, list_corpora, get_file, get_corpus, and delete_corpus APIs. Could you please assist in resolving this problem or provide guidance on how to increase the quota? The specific service/metric causing the issue isn't listed on the quota page. This limitation is significantly delaying the deployment process.

**Comment by davidADSP** [comment]
I'm also having this issue.

**Comment by kunj-gandhi12** [comment]
haven't found this service in Quota page yet. Any update on this?

**Comment by Guthman** [comment]
Running into the same issue. Managing and monitoring the corpora becomes quite difficult like this. If any one has a robust, temporary workaround to be able to list all the files in a corpus, I'm interested.

**Comment by yinghsienwu** [comment]
You can list all the files in a corpus using `vertexai.preview.rag.list_files(corpus_name)`. Quota wise, we are asking the backend team to answer.
