### ISSUE TITLE
TypeError: Couldn't build proto file into descriptor pool: duplicate symbol 

### ISSUE THREAD

**Issue by DamyanBG** [googleapis/python-aiplatform#4557]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-aiplatform/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: Windows, Linux
  - Python version: python 3.13.0
  - pip version: no matter
  - `google-cloud-aiplatform` version: 1.70.0

#### Steps to reproduce

  Just build the image with Python 3.13.0 and start the container.

#### Code example

[Example repo](https://github.com/DamyanBG/min-repo-protobuf-bug)

#### Stack trace
```
Traceback (most recent call last): File "/app/main.py", line 1, in import vertexai File "/usr/local/lib/python3.13/site-packages/vertexai/init.py", line 19, in from google.cloud.aiplatform import version as aiplatform_version File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform/init.py", line 24, in from google.cloud.aiplatform import initializer File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform/initializer.py", line 35, in from google.cloud.aiplatform import compat File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform/compat/init.py", line 18, in from google.cloud.aiplatform.compat import services File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform/compat/services/init.py", line 18, in from google.cloud.aiplatform_v1beta1.services.dataset_service import ( client as dataset_service_client_v1beta1, ) File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform_v1beta1/init.py", line 21, in from .services.dataset_service import DatasetServiceClient File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform_v1beta1/services/dataset_service/init.py", line 16, in from .client import DatasetServiceClient File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform_v1beta1/services/dataset_service/client.py", line 53, in from google.cloud.aiplatform_v1beta1.services.dataset_service import pagers File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform_v1beta1/services/dataset_service/pagers.py", line 40, in from google.cloud.aiplatform_v1beta1.types import annotation File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform_v1beta1/types/init.py", line 31, in from .batch_prediction_job import ( BatchPredictionJob, ) File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform_v1beta1/types/batch_prediction_job.py", line 26, in from google.cloud.aiplatform_v1beta1.types import explanation File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform_v1beta1/types/explanation.py", line 22, in from google.cloud.aiplatform_v1beta1.types import explanation_metadata File "/usr/local/lib/python3.13/site-packages/google/cloud/aiplatform_v1beta1/types/explanation_metadata.py", line 33, in class ExplanationMetadata(proto.Message): ...<570 lines>... ) File "/usr/local/lib/python3.13/site-packages/proto/message.py", line 279, in new file_info.generate_file_pb(new_class=cls, fallback_salt=full_name) ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/proto/_file_info.py", line 104, in generate_file_pb pool.Add(self.descriptor) ~~~~~~~~^^^^^^^^^^^^^^^^^ TypeError: Couldn't build proto file into descriptor pool: duplicate symbol 'google.cloud.aiplatform.v1beta1.ExplanationMetadata.InputMetadata.Visualization.firstlineno'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by DamyanBG** [comment]
Very good, thank you!
